function MathUtil(){MathUtil.MACHINE_EPSILON}MathUtil.MACHINE_EPSILON=function(){for(var a=1;1!=.5*a+1;)a*=.5;return a}();MathUtil.MACHINE_EPSILON_ROOT=Math.sqrt(MathUtil.MACHINE_EPSILON);
MathUtil.gradientDescent=function(a,b,c,d){var e;d=d||1E-7;if(b.length!=a.length)throw"The number of parameters does not match initial point length.";var f=0;do{e=Vector.clone(b);for(var g=0;g<a.length;g++)b[g]=e[g]-c*MathUtil.partialDerivative(a,{withRespectTo:g,at:e});f++}while(Vector.scalarDifference(b,e)>d);return b};
MathUtil.linearRegression=function(a){var b=function(b,d){for(var e=0,f=0;f<a.length;f++)e+=(b+d*a[f][0]-a[f][1])*(b+d*a[f][0]-a[f][1]);return e};MathUtil.gradientDescent(b,[0,0],.001);return MathUtil.gradientDescent(b,[1,1],.01)};MathUtil.gcd=function(a,b){return b?MathUtil.gcd(b,a%b):a};MathUtil.derivative=function(a,b,c){if(1<this.eval.length)throw"This is a multivariable function. Use partial derivative method.";var d=MathUtil.MACHINE_EPSILON_ROOT*b;c=c||d;return(a(b+c)-a(b-c))/(2*c)};
MathUtil.partialDerivative=function(a,b){var c=MathUtil.MACHINE_EPSILON_ROOT*b.at[b.withRespectTo];b.error=b.error||c;if(!Array.isArray(b.at))throw"The partialDerivative 'at' paramater must be an array.";c=Vector.clone(b.at);c[b.withRespectTo]-=b.error;var d=Vector.clone(b.at);d[b.withRespectTo]+=b.error;return(a.apply(this,d)-a.apply(this,c))/(2*b.error)};function Quotient(a,b){this.numerator=a;this.denominator=b}
Quotient.prototype.add=function(a){return new Quotient(this.numerator*a.denominator+a.numerator*this.denominator,a.denominator*this.denominator)};Quotient.prototype.subtract=function(a){return new Quotient(this.numerator*a.denominator-a.numerator*this.denominator,a.denominator*this.denominator)};Quotient.prototype.simplify=function(){var a=MathUtil.gcd(this.numerator,this.denominator);this.numerator/=a;this.denominator/=a};
Quotient.prototype.multiply=function(a){return new Quotient(this.numerator*a.numerator,this.denominator*a.denominator)};Quotient.prototype.sProduct=function(a){return new Quotient(this.numerator*a,this.denominator*a)};function Matrix(){this.matrixArray=[];if(Array.isArray(arguments[0])&&Array.isArray(arguments[0][0]))for(var a=0;a<arguments[0].length;a++)this.matrixArray.push(arguments[0][a]);else for(a=0;a<arguments.length;a++)this.matrixArray.push(arguments[a]);this.width=this.matrixArray[0].length;this.height=this.matrixArray.length;this.rational=!1}
Matrix.prototype.rationalize=function(){for(var a=0;a<this.height;a++)for(var b=0;b<this.width;b++)this.matrixArray[a][b]=new Quotient(this.matrixArray[a][b],1);this.rational=!0};Matrix.prototype.sProduct=function(a){for(var b=0;b<this.matrixArray.length;b++)Vector.sProduct(this.matrixArray[b],a)};
Matrix.prototype.mProduct=function(a){if(a.width!=this.height)console.warn("mProduct failed due to incompatible matrix dimensions.");else{for(var b=[],c=0;c<this.height;c++){b.push([]);for(var d=0;d<this.width;d++)b[c].push(Vector.dot(this.matrixArray[c],a.getColumnVector(d)))}return new Matrix(b)}};Matrix.prototype.vProduct=function(a){for(var b=new Vector,c=0;c<this.height;c++)b.push(Vector.dot(this.matrixArray[c],a));return b};
Matrix.prototype.getColumnVector=function(a){for(var b=[],c=0;c<this.height;c++)b.push(this.matrixArray[c][a]);return b};Matrix.prototype.print=function(){for(var a=0;a<this.height;a++){for(var b="|",c=0;c<this.width;c++)b+=this.matrixArray[a][c]+" ";b+="|";console.log(b)}};Matrix.prototype.transpose=function(){for(var a=[],b=0;b<this.width;b++)a.push(this.getColumnVector(b));this.matrixArray=a;this.height=a.length;this.width=a[0].length};Matrix.prototype.at=function(a,b){return this.matrixArray[a][b]};
Matrix.prototype.inverse=function(){if(this.width!=this.height)console.warn("inversion failed. Matrix is not square.");else if(0!=this.determinant){var a=this.adjoint();a.sProduct(1/this.determinant());return a}};
Matrix.prototype.determinant=function(){if(this.width!=this.height)console.warn("determinant failed. Matrix is not square.");else{if(2==this.width)return this.at(0,0)*this.at(1,1)-this.at(1,0)*this.at(0,1);for(var a=1,b=0,c=0;c<this.width;c++)var d=this.minor(0,c),b=b+a*this.at(0,c)*d.determinant(),a=-1*a;return b}};Matrix.prototype.clone=function(){return new Matrix(this.matrixArray)};
Matrix.prototype.minor=function(a,b){for(var c=[],d=0;d<this.height;d++)if(d!=a){c.push([]);for(var e=0;e<this.width;e++)e!=b&&c[c.length-1].push(this.matrixArray[d][e])}return new Matrix(c)};Matrix.prototype.cofactorMatrix=function(){for(var a=[],b=1,c=0;c<this.height;c++){a.push([]);for(var d=b,e=0;e<this.width;e++){var f=this.minor(c,e);a[c][e]=f.determinant()*d;d*=-1}b*=-1}return new Matrix(a)};Matrix.prototype.adjoint=function(){var a=this.cofactorMatrix();a.transpose();return a};
Matrix.prototype.set=function(a,b,c){this.matrixArray[a][b]=c};Matrix.prototype.solve=function(a){if(0!=this.determinant()){var b=this.clone();b.gaussianElimination(a);return b.backSubstitution(a)}};
Matrix.prototype.backSubstitution=function(a){if(a.length!=this.height)console.warn("backSubstitution failed due to incompatible array-matrix dimensions.");else{for(var b=0,c=[a[a.length-1]/this.matrixArray[this.height-1][this.width-1]],b=this.height-2;0<=b;b--){var d=this.matrixArray[b].slice(b+1,this.width),d=(a[b]-Vector.dot(d,c))/this.matrixArray[b][b];c.unshift(d)}return c}};
Matrix.prototype.gaussianElimination=function(a,b){if(a.length!=this.height)console.warn("gaussianElimination failed due to incompatible array-matrix dimensions.");else for(var c=0;c<this.height;c++)for(var d=c+1;d<this.height;d++){var e=this.at(d,c)/this.at(c,c);a[d]-=e*a[c];for(var f=0;f<this.width;f++)this.matrixArray[d][f]-=e*this.at(c,f)}};function MatrixUtil(){}MatrixUtil.FLOAT_32_ARRAY=!0;MatrixUtil.ARRAY=!1;MatrixUtil.type=MatrixUtil.FLOAT_32_ARRAY;MatrixUtil.matrixSize=3;MatrixUtil.plus=function(a,b){for(var c=MatrixUtil.createEmptyMatrix(a.length),d=0;d<a.length;d++)c[d]=a[d]+b[d];return c};MatrixUtil.minus=function(a,b){for(var c=MatrixUtil.createEmptyMatrix(a.length),d=0;d<a.length;d++)c[d]=a[d]-b[d];return c};MatrixUtil.sProduct=function(a,b){for(var c=MatrixUtil.createEmptyMatrix(a.length),d=0;d<a.length;d++)c[d]=a[d]*b;return c};
MatrixUtil.vProduct=function(a,b){MatrixUtil.warnIfWrongSize(a.length);MatrixUtil.warnIfWrongSize(b.length*b.length);for(var c=MatrixUtil.createEmptyMatrix(b.length),d=0;d<c.length;d++)c[d]=Vector.dot(MatrixUtil.getRowAsArray(a,d+1),b);return c};
MatrixUtil.mProduct=function(a,b){MatrixUtil.warnIfWrongSize(a.length);MatrixUtil.warnIfWrongSize(b.length);for(var c=MatrixUtil.createEmptyMatrix(a.length),d=0;d<MatrixUtil.matrixSize;d++)for(var e=0;e<MatrixUtil.matrixSize;e++){var f=Vector.dot(MatrixUtil.getRowAsArray(a,d+1),MatrixUtil.getColumnAsArray(b,e+1));MatrixUtil.setElementAtIndex(c,d+1,e+1,f)}return c};
MatrixUtil.setElementAtIndex=function(a,b,c,d){MatrixUtil.warnIfWrongSize(a.length);var e=MatrixUtil.convertMatrixIndexToArrayIndex(b,c);MatrixUtil.matrixIndexOutOfBounds(a,b,c,e);a[e]=d};MatrixUtil.getElementAtIndex=function(a,b,c){MatrixUtil.warnIfWrongSize(a.length);var d=MatrixUtil.convertMatrixIndexToArrayIndex(b,c);MatrixUtil.matrixIndexOutOfBounds(a,b,c,d);return a[d]};
MatrixUtil.matrixIndexOutOfBounds=function(a,b,c,d){if(d>a.length-1||0>d)throw"MatrixIndexOutOfBoundsError: The index ("+b+", "+c+") is out of bounds.";};MatrixUtil.convertMatrixIndexToArrayIndex=function(a,b){return(a-1)*MatrixUtil.matrixSize+(b-1)};MatrixUtil.createEmptyMatrix=function(a){var b;switch(MatrixUtil.type){case MatrixUtil.FLOAT_32_ARRAY:b=new Float32Array(a);break;case MatrixUtil.ARRAY:b=Array(a);break;default:MatrixUtil.wrongTypeError()}return b};
MatrixUtil.logMatrix=function(a){MatrixUtil.warnIfWrongSize(a.length);for(var b="",c=1;c<=MatrixUtil.matrixSize;c++){for(var b=b+"|",d=1;d<MatrixUtil.matrixSize;d++)b+=MatrixUtil.getElementAtIndex(a,c,d)+", ";b+=MatrixUtil.getElementAtIndex(a,c,d)+"|\n"}console.log(b)};MatrixUtil.getRowAsArray=function(a,b){MatrixUtil.warnIfWrongSize(a.length);for(var c=MatrixUtil.createEmptyMatrix(MatrixUtil.matrixSize),d=0;d<MatrixUtil.matrixSize;d++)c[d]=MatrixUtil.getElementAtIndex(a,b,d+1);return c};
MatrixUtil.getColumnAsArray=function(a,b){MatrixUtil.warnIfWrongSize(a.length);for(var c=MatrixUtil.createEmptyMatrix(MatrixUtil.matrixSize),d=0;d<MatrixUtil.matrixSize;d++)c[d]=MatrixUtil.getElementAtIndex(a,d+1,b);return c};MatrixUtil.warnIfWrongSize=function(a){return a!=MatrixUtil.matrixSize*MatrixUtil.matrixSize?(console.warn("WrongSizeWarning: A matrix passed in to MatrixUtil is not the size specified by matrixSize <"+MatrixUtil.matrixSize+">"),!0):!1};
MatrixUtil.createTransformationMatrix=function(a){a||(a={});0==a.rotationX||a.rotationX||(a.rotationX=0);0==a.rotationY||a.rotationY||(a.rotationY=0);0==a.rotationZ||a.rotationZ||(a.rotationZ=0);0==a.shiftX||a.shiftX||(a.shiftX=0);0==a.shiftY||a.shiftY||(a.shiftY=0);0==a.shiftZ||a.shiftZ||(a.shiftZ=0);var b=MatrixUtil.createRotationXMatrix(a.rotationX),c=MatrixUtil.createRotationYMatrix(a.rotationY),d=MatrixUtil.createRotationZMatrix(a.rotationZ);a=MatrixUtil.createTranslationMatrix(a.shiftX,a.shiftY,
a.shiftZ);var e=MatrixUtil.mProduct;return e(e(e(b,c),d),a)};MatrixUtil.createRotationXMatrix=function(a){var b=Math.cos(a);a=Math.sin(a);return MatrixUtil.createMatrix([1,0,0,0,0,b,-a,0,0,a,b,0,0,0,0,1])};MatrixUtil.createRotationYMatrix=function(a){var b=Math.cos(a);a=Math.sin(a);return MatrixUtil.createMatrix([b,0,a,0,0,1,0,0,-a,0,b,0,0,0,0,1])};MatrixUtil.createRotationZMatrix=function(a){var b=Math.cos(a);a=Math.sin(a);return MatrixUtil.createMatrix([b,-a,0,0,a,b,0,0,0,0,1,0,0,0,0,1])};
MatrixUtil.createTranslationMatrix=function(a,b,c){return MatrixUtil.createMatrix([1,0,0,a,0,1,0,b,0,0,1,c,0,0,0,1])};MatrixUtil.createMatrix=function(a){var b;switch(MatrixUtil.type){case MatrixUtil.FLOAT_32_ARRAY:b=new Float32Array(a);break;case MatrixUtil.ARRAY:b=a;break;default:MatrixUtil.wrongTypeError()}return b};MatrixUtil.wrongTypeError=function(){throw"WrongTypeError: MatrixUtil.type must be set to either MatrixUtil.FLOAT_32_ARRAY or MatrixUtil.ARRAY";};function Vector(){}Vector.cross=function(a,b){if(3==a.length&&3==b.length)return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]};Vector.sProduct=function(a,b){for(var c=0;c<a.length;c++)a[c]*=b};Vector.clone=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];return b};Vector.dot=function(a,b){for(var c=0,d=0;d<a.length;d++)c+=a[d]*b[d];return c};Vector.print=function(a){for(var b="<",c=0;c<a.length;c++)b+=a[c]+" ";console.log(b+">")};
Vector.scalarDifference=function(a,b){for(var c=0,d=0;d<a.length;d++)c+=a[d]-b[d];return c};Vector.draw2DVector=function(a,b,c){var d=a.strokeStyle,e=a.fillStyle;a.strokeStyle=c;a.fillStyle=c;a.beginPath();a.moveTo(0,0);a.lineTo(b[0],b[1]);a.stroke();a.fillRect(b[0],b[1],5,5);a.strokeStyle=d;a.fillStyle=e};